-- 7. Ad Revenue v. Circulation ROI
-- Which cities had the highest ad revenue per net circulated copy?
-- Is this ratio improving or worsening over time?
SELECT * FROM fact_ad_revenue;

With circulation AS (
	SELECT
        dc.city,
        CAST(RIGHT(ar.quarter, 4) AS UNSIGNED) AS year,
        SUM(ps.net_circulation) as total_circulation,
        SUM(ar.ad_revenue_inr) as total_revenue
    FROM fact_print_sales ps
    LEFT JOIN dim_city dc
		ON dc.city_id = ps.city_id
	LEFT JOIN fact_ad_revenue ar
		ON ar.edition_id = ps.edition_id
	GROUP BY dc.city, CAST(RIGHT(ar.quarter, 4) AS UNSIGNED) 
)
SELECT 
	city,
    year,
    total_revenue,
    total_circulation,
    ROUND(CAST(total_revenue AS FLOAT) / NULLIF(total_circulation, 0), 2) AS circulation_roi,
    RANK() OVER(
		PARTITION BY year 
        ORDER BY ROUND(total_revenue / NULLIF(total_circulation, 0), 2) DESC
        ) AS ranked_roi,
    RANK() OVER(
		PARTITION BY year
        ORDER BY total_revenue DESC
        ) AS ranked_revenue,
	RANK() OVER(
		ORDER BY ROUND(total_revenue / NULLIF(total_circulation, 0), 2) DESC
        ) AS ranked_circulation
FROM circulation
ORDER BY city, year ASC, circulation_roi DESC;




-- INSIGHT
-- a. Patna performed the best overall pulling in ~INR 17 Billion
--    and an ROI of INR 15.04 per copy sold from 1.1 Billion copies of newspapers sold
-- b. Lucknow recorded the most efficient ROI (INR 18.16 revenue per paper sold)
--    Having also pulled in the 5th highest ad revenue of about INR 16 Billion.
-- c. Varanasi recorded the lowest ROI with INR 7.11 revenue per paper sold with the 
--    2nd lowest revenue generated by the city (INR 14 Billion), even with the 2nd highest 
--    circulation volume (2.07 Billion copies). This indicates an inefficiency of ad-marketing; we should
--    be leveraging on the numbers there to drive ad revenue. Untapped potential!
-- d. Jaipur presents a strong opportunity with a large potential market for improved ad revenue as the city
--    is the most populated (2.09 Billion people). The city made the 4th highest revenue (~INR 16.4 Billion)
--    but recorded the second to the lowest ROI of 7.88 per copy sold. 

-- Revenue Trends
-- a. Patna recorded a steady increase in revenue from 2022 to 2024 after experiencing a slight
--    dip between 2020 and 2021. Lowest recorded ROI was INR 12.3/copy sold (2020) and highest 
--    ROI was INR 18.54/copy sold (2024)
-- b. Lucknow maintained high ROI from 2019 - 2024 (between INR 18.57 and INR 20.31) with the lowest
--    ROI recorded being in 2020 (INR 15.97).
-- c. Fluctuations; cities like Bhopal, Ahmedabad, Delhi, Jaipur, Mumbai, Ranchi recorded wild fluctuations in ROI
--    with all but Jaipur, and Ranchi ending 2024 with an improved ROI from 2019.


-- Recommendations
-- a. Focus ad optimization and pricing strategies in cities with high-circulation but low-roi e.g.,
--    Varanasi and Jaipur), to leverage population and already impressive revenue to improve ROI.
-- b. Retain successful ad models from Lucknow and Patna as efficiency benchmarks
